// 63-drop-pdf.spec.js — drop a PDF onto the terminal → server uploads it
// to <workingDir>/.claude-attachments/ → client injects `@<absPath>` as
// terminal input. Per docs/specs/file-browser.md "Generic file drop"
// + commits 41993c0/a166689 (server) + 409b440 (client).

const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { createServer } = require('../helpers/server-factory');
const {
  waitForAppReady,
  waitForTerminalCanvas,
  setupPageCapture,
  attachFailureArtifacts,
  joinSessionAndStartTerminal,
} = require('../helpers/terminal-helpers');
const {
  makeFixtureDir,
  cleanupFixture,
  dispatchDrop,
} = require('../helpers/file-browser-v2-helpers');

// Minimal valid PDF (single empty page) — generated by `pdftk` years
// ago, kept inline so the test has zero file-system fixture dependency.
// Bytes from the canonical "smallest valid PDF" example. base64 of a
// hand-assembled minimum PDF (no compression, single page, empty
// content stream).
const TINY_PDF_BASE64 =
  'JVBERi0xLjEKJeLjz9MKMSAwIG9iago8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFI+P' +
  'gplbmRvYmoKMiAwIG9iago8PC9UeXBlL1BhZ2VzL0NvdW50IDEvS2lkc1szIDAgUl0+P' +
  'gplbmRvYmoKMyAwIG9iago8PC9UeXBlL1BhZ2UvUGFyZW50IDIgMCBSL01lZGlhQm94W' +
  'zAgMCAxMDAgMTAwXS9SZXNvdXJjZXM8PD4+L0NvbnRlbnRzIDQgMCBSPj4KZW5kb2JqC' +
  'jQgMCBvYmoKPDwvTGVuZ3RoIDA+PgpzdHJlYW0KZW5kc3RyZWFtCmVuZG9iagp4cmVmC' +
  'jAgNQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTUgMDAwMDAgbiAKMDAwMDAwM' +
  'DA2MyAwMDAwMCBuIAowMDAwMDAwMTE0IDAwMDAwIG4gCjAwMDAwMDAyMTAgMDAwMDAgb' +
  'iAKdHJhaWxlcgo8PC9TaXplIDUvUm9vdCAxIDAgUj4+CnN0YXJ0eHJlZgoyNjMKJSVFT' +
  '0YK';

test.describe('Drop generic file: PDF', () => {
  let server, port, url;
  let fixture;

  test.beforeAll(async () => {
    fixture = makeFixtureDir('drop-pdf');
    ({ server, port, url } = await createServer());
  });

  test.afterAll(async () => {
    if (server) await server.close();
    cleanupFixture(fixture);
  });

  test.afterEach(async ({ page }, testInfo) => {
    await attachFailureArtifacts(page, testInfo);
  });

  async function setupSession(page) {
    setupPageCapture(page);
    const sessionId = await page.evaluate(async ({ origin, name, wd }) => {
      const resp = await fetch(origin + '/api/sessions/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, workingDir: wd }),
      });
      const data = await resp.json();
      return data.sessionId;
    }, { origin: url, name: 'drop-pdf', wd: fixture });
    await page.goto(url);
    await waitForAppReady(page);
    await waitForTerminalCanvas(page);
    await joinSessionAndStartTerminal(page, sessionId);
    return sessionId;
  }

  test('drop a PDF onto the terminal → @<path> injected as input', async ({ page }) => {
    await setupSession(page);

    // Sanity: generic-drop handler is wired on the active terminal.
    const wired = await page.evaluate(() => !!(window.app && window.app._genericDropHandler));
    expect(wired, 'generic drop handler should be wired').toBe(true);

    // Dispatch the drop carrying a single PDF File.
    await dispatchDrop(page, '#terminal', [{
      name: 'tiny.pdf',
      mimeType: 'application/pdf',
      base64: TINY_PDF_BASE64,
    }]);

    // Wait for the @<path> to land in the terminal buffer. The
    // production flow: dispatchDrop → uploadOne → POST /api/files/upload
    // → resp.path → buildAtPathInjection(absPath) → injectAtPath
    // wraps in bracketed-paste, sends as input WS frame → server
    // forwards to PTY → shell echoes back → xterm renders.
    //
    // We assert on the terminal-buffer contents (the user-visible
    // ground truth) rather than the WS message capture: bracketed-paste
    // wrapping introduces ESC bytes inside the JSON `data` field, and
    // the visible-text assertion is closer to what a human verifies.
    const expectedFragments = ['@', '.claude-attachments', 'tiny.pdf'];
    await page.waitForFunction((needles) => {
      const term = window.app && window.app.terminal;
      if (!term) return false;
      const buf = term.buffer.active;
      let combined = '';
      for (let i = 0; i < buf.length; i++) {
        const line = buf.getLine(i);
        if (line) combined += line.translateToString(true);
      }
      return needles.every((n) => combined.includes(n));
    }, expectedFragments, { timeout: 15000 });

    // The file actually landed on disk inside the fixture.
    const attachmentsDir = path.join(fixture, '.claude-attachments');
    expect(fs.existsSync(attachmentsDir), '.claude-attachments dir should exist').toBe(true);
    const dropped = fs.readdirSync(attachmentsDir);
    expect(dropped.some((f) => f.endsWith('tiny.pdf')),
      'tiny.pdf should have been written inside .claude-attachments/').toBe(true);
  });

  test('drop a LARGE (512KB) non-image file → uploads intact (bytes round-trip)', async ({ page }) => {
    // The real-world regression: before the parser fix, the global
    // express.json() (~100KB) 413'd any base64 body over ~75KB BEFORE the
    // upload route ran, so normal-sized non-image files silently failed.
    // This drives the full browser path — drop → FileReader → base64 → POST
    // → server decode → writeFile — with a 512KB payload (~683KB JSON body,
    // well over the old limit) and asserts the bytes on disk EQUAL the bytes
    // dropped. The tiny-PDF test above would have passed even pre-fix.
    await setupSession(page);

    // Deterministic, non-trivial 512KB payload so we can verify integrity.
    const big = Buffer.alloc(512 * 1024);
    for (let i = 0; i < big.length; i++) big[i] = (i * 31 + 7) & 0xff;
    const sha = crypto.createHash('sha256').update(big).digest('hex');

    await dispatchDrop(page, '#terminal', [{
      name: 'large.bin',
      mimeType: 'application/octet-stream',
      base64: big.toString('base64'),
    }]);

    // @<path> injected → upload succeeded (no error toast path).
    const expectedFragments = ['@', '.claude-attachments', 'large.bin'];
    await page.waitForFunction((needles) => {
      const term = window.app && window.app.terminal;
      if (!term) return false;
      const buf = term.buffer.active;
      let combined = '';
      for (let i = 0; i < buf.length; i++) {
        const line = buf.getLine(i);
        if (line) combined += line.translateToString(true);
      }
      return needles.every((n) => combined.includes(n));
    }, expectedFragments, { timeout: 15000 });

    // The decisive check: the file on disk is byte-for-byte what we dropped.
    const attachmentsDir = path.join(fixture, '.claude-attachments');
    const match = fs.readdirSync(attachmentsDir).find((f) => f.endsWith('large.bin'));
    expect(match, 'large.bin should exist in .claude-attachments/').toBeTruthy();
    const onDisk = fs.readFileSync(path.join(attachmentsDir, match));
    expect(onDisk.length, 'uploaded byte length should match').toBe(big.length);
    expect(crypto.createHash('sha256').update(onDisk).digest('hex'),
      'uploaded bytes should round-trip exactly (no corruption / truncation)').toBe(sha);
  });
});
