#!/usr/bin/env node
'use strict';

// mesh-lock.js — single source of truth for the mesh sidecar's identity and
// integrity. It maintains mesh-sidecar.lock.json:
//
//   {
//     "version": "1.0.0",                // friendly display label
//     "contentHash": "<sha256 hex>",     // hash of the sidecar SOURCE
//     "assets": { "<assetName>": "<sha256>" , ... }  // per-binary checksums
//   }
//
// contentHash is derived purely from source files (Go-free — no toolchain
// needed), so it can be recomputed in a PR check and locally. It keys the
// GitHub release tag `mesh-<contentHash>` and CI build-skip. The per-asset
// checksums require the BUILT binaries (CI only) and are what the installer
// verifies the download against — they ship inside the npm tarball so trust is
// anchored by the signed npm package, not by a file fetched from the same
// mutable release.
//
// Modes:
//   node scripts/mesh-lock.js                 # rewrite version+contentHash (preserve assets)
//   node scripts/mesh-lock.js --check         # assert committed contentHash is current (exit 1 if stale)
//   node scripts/mesh-lock.js --assets <dir>  # fill asset checksums from built binaries in <dir>
//   node scripts/mesh-lock.js --embed <file>  # fill asset checksums from a checksums.txt manifest
//   node scripts/mesh-lock.js --print-hash    # print the computed contentHash and exit

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const LOCK_PATH = path.join(ROOT, 'mesh-sidecar.lock.json');

// The full platform matrix. MUST stay in lock-step with assetName() in
// src/utils/sidecar-installer.js and the emit() calls in build-mesh-sidecar.sh.
const ASSET_NAMES = [
  'aiordie-mesh-windows-amd64.exe',
  'aiordie-mesh-windows-arm64.exe',
  'aiordie-mesh-linux-amd64',
  'aiordie-mesh-linux-arm64',
  'aiordie-mesh-darwin-amd64',
  'aiordie-mesh-darwin-arm64',
];

// Source files whose content defines the sidecar binary. A change to any of
// these flips contentHash → a new release tag → a rebuild. We walk mesh/
// RECURSIVELY for *.go (+ go.mod) so a future sub-package is captured, and the
// build script (a flag/ldflags change). go.sum is intentionally EXCLUDED: it is
// generated by `go mod tidy` at build time (not committed), so including it
// would make contentHash differ between a Go-free local/PR checkout and the CI
// build — go.mod already pins the dependency versions.
// Paths are returned POSIX-normalized so the SORT (and the hash) are identical
// on Windows and on the Linux CI runner.
function sourceFiles() {
  const out = [];
  const meshDir = path.join(ROOT, 'mesh');
  (function walk(dir) {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, ent.name);
      if (ent.isDirectory()) { walk(abs); continue; }
      if (ent.isFile() && (ent.name.endsWith('.go') || ent.name === 'go.mod')) {
        out.push(path.relative(ROOT, abs).split(path.sep).join('/'));
      }
    }
  })(meshDir);
  out.push('scripts/build-mesh-sidecar.sh');
  return out.sort();
}

function sha256File(abs) {
  return crypto.createHash('sha256').update(fs.readFileSync(abs)).digest('hex');
}

function sha256Bytes(buf) {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

// Deterministic: normalize CRLF→LF so the hash is identical on Windows and POSIX
// checkouts (git autocrlf would otherwise change the bytes and the hash).
function computeContentHash() {
  const h = crypto.createHash('sha256');
  for (const rel of sourceFiles()) {
    const abs = path.join(ROOT, rel);
    if (!fs.existsSync(abs)) throw new Error(`mesh source missing: ${rel}`);
    const norm = fs.readFileSync(abs).toString('binary').replace(/\r\n/g, '\n');
    h.update(rel.replace(/\\/g, '/'));
    h.update('\0');
    h.update(crypto.createHash('sha256').update(Buffer.from(norm, 'binary')).digest('hex'));
    h.update('\n');
  }
  return h.digest('hex');
}

function readLock() {
  if (!fs.existsSync(LOCK_PATH)) return { version: '1.0.0', contentHash: '', assets: {} };
  return JSON.parse(fs.readFileSync(LOCK_PATH, 'utf8'));
}

function writeLock(lock) {
  // Stable key order + trailing newline for clean diffs.
  const ordered = {
    version: lock.version || '1.0.0',
    contentHash: lock.contentHash || '',
    assets: {},
  };
  for (const name of ASSET_NAMES) {
    if (lock.assets && lock.assets[name]) ordered.assets[name] = lock.assets[name];
  }
  fs.writeFileSync(LOCK_PATH, JSON.stringify(ordered, null, 2) + '\n');
}

function parseChecksums(text) {
  // "<sha256>  <assetname>" per line (sha256sum output).
  const out = {};
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t) continue;
    const parts = t.split(/\s+/);
    if (parts.length >= 2) out[parts[1]] = parts[0].toLowerCase();
  }
  return out;
}

function main() {
  const args = process.argv.slice(2);
  const contentHash = computeContentHash();

  if (args[0] === '--print-hash') {
    process.stdout.write(contentHash + '\n');
    return;
  }

  if (args[0] === '--check') {
    const lock = readLock();
    if (lock.contentHash !== contentHash) {
      console.error('mesh-sidecar.lock.json is STALE.');
      console.error(`  committed contentHash: ${lock.contentHash || '(none)'}`);
      console.error(`  computed  contentHash: ${contentHash}`);
      console.error('  Run `node scripts/mesh-lock.js` and commit the result.');
      process.exit(1);
    }
    console.log(`mesh-sidecar.lock.json is current (contentHash ${contentHash.slice(0, 12)}…).`);
    return;
  }

  // Publish-time gate: the lock must carry a valid SHA-256 for EVERY platform
  // (not merely "6 keys"), so the npm tarball can never ship a partial/garbage
  // asset map that breaks installs on one platform.
  if (args[0] === '--assert-complete') {
    const lock = readLock();
    const bad = [];
    for (const name of ASSET_NAMES) {
      const h = (lock.assets && lock.assets[name]) || '';
      if (!/^[a-f0-9]{64}$/.test(h)) bad.push(`${name}: ${h ? 'invalid sha256' : 'missing'}`);
    }
    if (lock.contentHash !== contentHash) bad.push(`contentHash stale (lock ${lock.contentHash}, source ${contentHash})`);
    if (bad.length) {
      console.error('mesh-sidecar.lock.json is NOT publish-ready:');
      for (const b of bad) console.error(`  - ${b}`);
      process.exit(1);
    }
    console.log('mesh-sidecar.lock.json is complete (6/6 valid checksums, hash current).');
    return;
  }

  const lock = readLock();
  lock.contentHash = contentHash;
  lock.assets = lock.assets || {};

  if (args[0] === '--assets') {
    const dir = args[1];
    if (!dir) { console.error('--assets requires a directory'); process.exit(1); }
    for (const name of ASSET_NAMES) {
      const abs = path.join(dir, name);
      if (fs.existsSync(abs)) lock.assets[name] = sha256File(abs);
    }
  } else if (args[0] === '--embed') {
    const file = args[1];
    if (!file) { console.error('--embed requires a checksums file'); process.exit(1); }
    const sums = parseChecksums(fs.readFileSync(file, 'utf8'));
    for (const name of ASSET_NAMES) {
      if (sums[name]) lock.assets[name] = sums[name];
    }
  }

  writeLock(lock);
  const filled = ASSET_NAMES.filter((n) => lock.assets[n]).length;
  console.log(`Wrote mesh-sidecar.lock.json (contentHash ${contentHash.slice(0, 12)}…, ${filled}/${ASSET_NAMES.length} assets).`);
}

module.exports = { computeContentHash, ASSET_NAMES, LOCK_PATH, parseChecksums, _sha256Bytes: sha256Bytes };

if (require.main === module) main();
